default_stage:
  default_modifiers:
    QuantizationModifier:
      config_groups:
        group_0:
          targets: [Linear]
          weights:
            num_bits: 8
            type: float
            symmetric: true
            group_size: null
            strategy: channel
            block_structure: null
            dynamic: false
            actorder: null
            scale_dtype: null
            zp_dtype: null
            observer: memoryless_minmax
            observer_kwargs: {}
          input_activations:
            num_bits: 8
            type: float
            symmetric: true
            group_size: null
            strategy: tensor
            block_structure: null
            dynamic: false
            actorder: null
            scale_dtype: null
            zp_dtype: null
            observer: memoryless_minmax
            observer_kwargs: {}
          output_activations: null
          format: null
      targets: [Linear]
      ignore: [lm_head]
      bypass_divisibility_checks: false
